### PR TITLE
Supported  date/time format in en-GB

### PR DESCRIPTION
**Pull request by Iyani-NK**
##  Fixed

- Fixed date/time format in EN-GB
eg: 3rd Dec 2020 13:00

- Fixed date/time format in EN-US
eg: Dec 3rd, 2020 1:00 PM

## Todo List

- [X] I have tested on an Android device.
- [X] I have tested on an iOS device.
- [X] I have added unit tests

### CODE REVIEW

**Comment by jonathanrandev** [comment]
So AM/PM suffix is going to be completely removed? 🤔

**Comment by Iyani-NK** [comment]
> So AM/PM suffix is going to be completely removed? 🤔

yes

**Comment by haavamoa** [comment]
After thinking more about it, I think we should support both en-US and en-GB. Breaking the current implementation is bad and it's no fun for consumers that are US citizens. Our desktop client handles both cases and we should to.

**Review by haavamoa — APPROVED** [review]
Looks good now.

Please remember to update the following wikis:
https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Converters#dateconverter
https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Converters#timeconverter
https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Converters#dateandtimeconverter

Before / After you release.

**Pull request merged**
