### PR TITLE
Fix for sheet broken when orientation changes

### PR DESCRIPTION
**Pull request by Vetle444**
## Fixed

- Fixed a bug where sheet disappeared or layout broken when orientation changed

## Todo List

- [X] I have tested on an Android device.
- [X] I have tested on an iOS device.
- [ ] I have added unit tests

>*Please add pictures / Gifs if possible*
>*Todo List can be checked by putting a `X` inside the brackets*
>*Remember to update our `wiki` after this PR is merged*

### CODE REVIEW

**Comment by haavamoa** [comment]
This should close #314

**Comment by haavamoa** [comment]
This will force the sheet to close and open, which means that the binding context will be re-created. As we do not know what people use sheet for, I think it's a good idea to not re-create the binding context. It also triggers events that it closes and opens, which can lead to some strange behaviours for consumers. 

Let's see if we can **Move** the sheet to the correct location without closing and opening it.

**Review by haavamoa — CHANGES_REQUESTED** [review]
This will force the sheet to close and open, which means that the binding context will be re-created and triggers close/open events. This can have some strange side effects for our consumers.

Let's see if we can Move the sheet to the correct location without closing and opening it.

**Review by haavamoa — APPROVED** [review]
If this worked then it looks good to me.

**Review by ErlingMK — APPROVED** [review]
Nice one 👍

**Pull request merged**
